# Generated by Django 5.1.4 on 2024-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "prdno",
                    models.CharField(
                        db_column="prdNo",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prdname",
                    models.CharField(
                        blank=True, db_column="prdName", max_length=20, null=True
                    ),
                ),
                (
                    "prdprice",
                    models.IntegerField(blank=True, db_column="prdPrice", null=True),
                ),
                (
                    "prdmaker",
                    models.CharField(
                        blank=True, db_column="prdMaker", max_length=30, null=True
                    ),
                ),
                (
                    "prdcolor",
                    models.CharField(
                        blank=True, db_column="prdColor", max_length=10, null=True
                    ),
                ),
                (
                    "ctgno",
                    models.CharField(
                        blank=True, db_column="ctgNo", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "managed": False,
            },
        ),
    ]
